The Cohere LLM has been integrated with the bot
TheZohan/roga-telegram-bot pull request #65
Opened 2024-09-17 16:06 UTC by liorLahav

1. Changed the LlmClient to be general 
2. Created both Openai and Cohere providers that the LlmClient uses 
3. Modified the prompts so both providers will act correctly 
4. Added a getPromptWithPerffixAndSuffix function
5. Modified the tests to work with general LlmClient

** Before reviewing keep in notice that you have to add to the env the following fields:
LLM_API_KEY= <API key > , LLM_PROVIDER_TYPE=cohere , LLM_MODEL=command-r-plus-08-2024

2024-09-18 06:01 UTC, TheZohan requested changes
There are a few small changes that needs to be done + A review by Liron

2024-09-18 16:28 UTC, liorLahav commented on src/prompts/prompts.yaml
> +    - Responed to the like you are a preson who is interested in their life and not a bot.
the bot sometimes would answer and state in its answer what it is doing for example three was a paragraph that started with **FOLLOWUP QUETION**

2024-09-18 16:32 UTC, liorLahav commented on src/prompts/prompts.yaml
> +   - Dont state the user what you are doing, just do it.
The bot sometimes would answer and state in its answer what it is doing for example three was a paragraph that started with **FOLLOWUP QUESTION**. i think this is necessary for the cohere to work as we want

2024-09-18 16:41 UTC, liorLahav commented on src/providers/CohereApi.ts
> +        preamble: userMessage == '' ? userMessage : systemMessage,
In case we want to summarize the user's message, The message itself is added to the prompt so there is no user message to send. The cohere must get at least one char in the message part so when there is a user message to send the prompt will be sent as the system prompt and if there isn't we will send the prompt as the message

2024-09-18 17:23 UTC, liorLahav commented on src/prompts/prompts.yaml
> +    - Responed to the like you are a preson who is interested in their life and not a bot.
Sometimes the bot wouldnt give a straight response For example, it had an opening that would seem a bit off

2024-09-21 16:44 UTC, TheZohan commented on src/prompts/prompts.yaml
> +    - Responed to the like you are a preson who is interested in their life and not a bot.
I will approve this change but I really prefer that prompt changes will be done separately. 
If there is such a problem that you identify lets discuss it in Whatsapp and research what to do together.
prompt changes must be in a separate commit....

2024-09-21 16:45 UTC, TheZohan commented on src/prompts/prompts.yaml
> +   - Dont state the user what you are doing, just do it.
Same as previous comment. I will approve but next time lets discuss before.

2024-09-21 16:48 UTC, TheZohan commented on src/providers/CohereApi.ts
> +        preamble: userMessage == '' ? userMessage : systemMessage,
I don't understnad :-) 
lets discuss this in a meeting. 
I believe it should be written differently anyways. In a function or at least a variable that explains the purpose of this code.

2024-09-29 10:55 UTC, closed without merging